package social

import (
	"bytes"
	"fmt"
	"image/color"
	"image/png"

	"github.com/fogleman/gg"
)

const (
	cardWidth  = 1200
	cardHeight = 630
)

// BacktestCardOpts holds the data for a backtest social card.
type BacktestCardOpts struct {
	Theme        string // "dark" | "light"
	StrategyName string
	Symbol       string
	Timeframe    string
	DateRange    string
	TotalReturn  float64
	SharpeRatio  float64
	MaxDrawdown  float64
	WinRate      float64
	EquityCurve  []float64 // y-values for sparkline
}

// SignalCardOpts holds the data for a signal social card.
type SignalCardOpts struct {
	Theme        string
	Symbol       string
	Direction    string // "LONG" | "SHORT"
	Price        float64
	StrategyName string
	Strength     float64
	Timestamp    string
}

// GenerateBacktestCard produces a 1200×630 PNG summarising a backtest.
func GenerateBacktestCard(opts BacktestCardOpts) ([]byte, error) {
	dc := gg.NewContext(cardWidth, cardHeight)

	bg, fg, accent, muted := themeColors(opts.Theme)
	dc.SetColor(bg)
	dc.Clear()

	// Brand text (top-left)
	dc.SetColor(accent)
	dc.DrawStringAnchored("trader-claude", 40, 40, 0, 1)

	// Strategy + symbol header
	dc.SetColor(fg)
	header := fmt.Sprintf("%s · %s · %s", opts.StrategyName, opts.Symbol, opts.Timeframe)
	dc.DrawStringAnchored(header, 40, 90, 0, 1)

	// Date range
	dc.SetColor(muted)
	dc.DrawStringAnchored(opts.DateRange, 40, 120, 0, 1)

	// Metric boxes (4 across)
	metrics := []struct {
		label string
		value string
		color color.Color
	}{
		{"Return", fmt.Sprintf("%+.1f%%", opts.TotalReturn*100), metricColor(opts.TotalReturn, accent)},
		{"Sharpe", fmt.Sprintf("%.2f", opts.SharpeRatio), accent},
		{"Max DD", fmt.Sprintf("%.1f%%", opts.MaxDrawdown*100), metricColor(opts.MaxDrawdown, accent)},
		{"Win Rate", fmt.Sprintf("%.0f%%", opts.WinRate*100), accent},
	}

	boxW := 240.0
	boxH := 80.0
	startX := 40.0
	startY := 170.0

	for i, m := range metrics {
		x := startX + float64(i)*(boxW+20)
		dc.SetColor(muted)
		dc.DrawRoundedRectangle(x, startY, boxW, boxH, 8)
		dc.Fill()

		dc.SetColor(m.color)
		dc.DrawStringAnchored(m.value, x+boxW/2, startY+25, 0.5, 0.5)
		dc.SetColor(fg)
		dc.DrawStringAnchored(m.label, x+boxW/2, startY+55, 0.5, 0.5)
	}

	// Equity sparkline
	if len(opts.EquityCurve) > 1 {
		drawSparkline(dc, opts.EquityCurve, 40, 300, float64(cardWidth)-80, 200, accent)
	}

	// Footer
	dc.SetColor(muted)
	dc.DrawStringAnchored("trader-claude · generated by AI", 40, float64(cardHeight)-30, 0, 0.5)

	return encodePNG(dc)
}

// GenerateSignalCard produces a 1200×630 PNG for a trading signal.
func GenerateSignalCard(opts SignalCardOpts) ([]byte, error) {
	dc := gg.NewContext(cardWidth, cardHeight)

	bg, fg, _, muted := themeColors(opts.Theme)
	dc.SetColor(bg)
	dc.Clear()

	// Direction color
	dirColor := color.RGBA{R: 0x22, G: 0xc5, B: 0x5e, A: 0xff} // green
	if opts.Direction == "SHORT" {
		dirColor = color.RGBA{R: 0xef, G: 0x44, B: 0x44, A: 0xff} // red
	}

	// Brand
	dc.SetColor(muted)
	dc.DrawStringAnchored("trader-claude", 40, 40, 0, 1)

	// Direction label (large)
	arrow := "▲"
	if opts.Direction == "SHORT" {
		arrow = "▼"
	}
	dc.SetColor(dirColor)
	dc.DrawStringAnchored(fmt.Sprintf("%s %s SIGNAL", arrow, opts.Direction), float64(cardWidth)/2, 180, 0.5, 0.5)

	// Symbol (large)
	dc.SetColor(fg)
	dc.DrawStringAnchored(opts.Symbol, float64(cardWidth)/2, 250, 0.5, 0.5)

	// Price
	dc.SetColor(dirColor)
	dc.DrawStringAnchored(fmt.Sprintf("$%.2f", opts.Price), float64(cardWidth)/2, 320, 0.5, 0.5)

	// Strategy + strength
	dc.SetColor(muted)
	dc.DrawStringAnchored(fmt.Sprintf("Strategy: %s", opts.StrategyName), float64(cardWidth)/2, 400, 0.5, 0.5)
	dc.DrawStringAnchored(fmt.Sprintf("Strength: %.0f%%", opts.Strength*100), float64(cardWidth)/2, 440, 0.5, 0.5)

	// Timestamp
	dc.DrawStringAnchored(opts.Timestamp, float64(cardWidth)/2, 500, 0.5, 0.5)

	// Footer
	dc.DrawStringAnchored("trader-claude", float64(cardWidth)/2, float64(cardHeight)-30, 0.5, 0.5)

	return encodePNG(dc)
}

// --- helpers ---

func themeColors(theme string) (bg, fg, accent, muted color.Color) {
	if theme == "light" {
		return color.White,
			color.RGBA{R: 0x1f, G: 0x29, B: 0x37, A: 0xff},
			color.RGBA{R: 0x37, G: 0x99, B: 0xff, A: 0xff},
			color.RGBA{R: 0x9c, G: 0xa3, B: 0xaf, A: 0x44}
	}
	return color.RGBA{R: 0x0f, G: 0x17, B: 0x2a, A: 0xff},
		color.RGBA{R: 0xf3, G: 0xf4, B: 0xf6, A: 0xff},
		color.RGBA{R: 0x37, G: 0x99, B: 0xff, A: 0xff},
		color.RGBA{R: 0x37, G: 0x41, B: 0x51, A: 0xff}
}

func metricColor(value float64, defaultColor color.Color) color.Color {
	if value >= 0 {
		return color.RGBA{R: 0x22, G: 0xc5, B: 0x5e, A: 0xff}
	}
	return color.RGBA{R: 0xef, G: 0x44, B: 0x44, A: 0xff}
}

func drawSparkline(dc *gg.Context, values []float64, x, y, w, h float64, lineColor color.Color) {
	minV, maxV := values[0], values[0]
	for _, v := range values {
		if v < minV {
			minV = v
		}
		if v > maxV {
			maxV = v
		}
	}
	rangeV := maxV - minV
	if rangeV == 0 {
		rangeV = 1
	}

	dc.SetColor(lineColor)
	dc.SetLineWidth(2)
	for i, v := range values {
		px := x + (float64(i)/float64(len(values)-1))*w
		py := y + h - ((v-minV)/rangeV)*h
		if i == 0 {
			dc.MoveTo(px, py)
		} else {
			dc.LineTo(px, py)
		}
	}
	dc.Stroke()
}

func encodePNG(dc *gg.Context) ([]byte, error) {
	var buf bytes.Buffer
	if err := png.Encode(&buf, dc.Image()); err != nil {
		return nil, fmt.Errorf("social: encode PNG: %w", err)
	}
	return buf.Bytes(), nil
}
