linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - depguard

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-rules:
    # Test files can ignore some checks
    - path: _test\.go
      linters:
        - errcheck

run:
  timeout: 5m
  modules-download-mode: readonly
